@baseUrl = http://127.0.0.1:8000/api

GET http://127.0.0.1:8000

###

#Регистрация
POST {{baseUrl}}/user/
Content-Type: application/json

{
    "username":"username6",
    "password":"password",
    "email":"test6@email.com"
}

###

#Получить токен
POST {{baseUrl}}/token/
Content-Type: application/json

{
    "email":"test6@email.com",
    "password":"password"
}

###

#Получить пользователя
GET {{baseUrl}}/user/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMTU2NTc5LCJpYXQiOjE2OTMxNTI5NzksImp0aSI6ImZkZmI4ZjhmOGI5YzRmNjJhNWY4Y2E5Y2U2NGFiNWZmIiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJ1c2VybmFtZTYifQ.LC0IZ9CMfwc_F1WlhoxfO2O_JoJ1apyxl3MqnoUYRcY

###

#Посмотреть контактную информацию
GET  {{baseUrl}}/user/contact/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMTU2NTc5LCJpYXQiOjE2OTMxNTI5NzksImp0aSI6ImZkZmI4ZjhmOGI5YzRmNjJhNWY4Y2E5Y2U2NGFiNWZmIiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJ1c2VybmFtZTYifQ.LC0IZ9CMfwc_F1WlhoxfO2O_JoJ1apyxl3MqnoUYRcY
###
# Изменить контактную информацию
PATCH {{baseUrl}}/user/contact/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMTU2NTc5LCJpYXQiOjE2OTMxNTI5NzksImp0aSI6ImZkZmI4ZjhmOGI5YzRmNjJhNWY4Y2E5Y2U2NGFiNWZmIiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJ1c2VybmFtZTYifQ.LC0IZ9CMfwc_F1WlhoxfO2O_JoJ1apyxl3MqnoUYRcY
Content-Type: application/json

{
    "user":5,
    "phone": "+79991112230",
    "country": "Россия",
    "region": "Москва",
    "locality": "Москва",
    "street": "Улица",
    "house": "7к2"
}
###
#Получить список продуктов
get {{baseUrl}}/product/
Content-Type: application/json

###

# Получить определенный продукт
GET {{baseUrl}}/product/4216292

###

#Получить информацию о продукте
GET {{baseUrl}}/productinfo/4216292

###

#добавить товар в корзину
POST {{baseUrl}}/orderitem/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMTU3NTcyLCJpYXQiOjE2OTMxNTM5NzIsImp0aSI6ImVlYzllMWM2MDE4NDQ2MjE4YzgzZjMyYmI3ZGQ3NWY1IiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJ1c2VybmFtZTYifQ.EtMihjHJ2s_kWUrHBcXW2P8OxSqhIB6ZDKxtcsU3DV8
Content-Type: application/json

{
    "product":"4216292",
    "quantity":1
}

###
POST {{baseUrl}}/orderitem/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMTU3NTcyLCJpYXQiOjE2OTMxNTM5NzIsImp0aSI6ImVlYzllMWM2MDE4NDQ2MjE4YzgzZjMyYmI3ZGQ3NWY1IiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJ1c2VybmFtZTYifQ.EtMihjHJ2s_kWUrHBcXW2P8OxSqhIB6ZDKxtcsU3DV8
Content-Type: application/json

{
    "product":"4216313",
    "quantity":1
}

###
# Просмотр корзины
GET {{baseUrl}}/orderitem/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMTU3NTcyLCJpYXQiOjE2OTMxNTM5NzIsImp0aSI6ImVlYzllMWM2MDE4NDQ2MjE4YzgzZjMyYmI3ZGQ3NWY1IiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJ1c2VybmFtZTYifQ.EtMihjHJ2s_kWUrHBcXW2P8OxSqhIB6ZDKxtcsU3DV8
###
GET {{baseUrl}}/order/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMTU3NTcyLCJpYXQiOjE2OTMxNTM5NzIsImp0aSI6ImVlYzllMWM2MDE4NDQ2MjE4YzgzZjMyYmI3ZGQ3NWY1IiwidXNlcl9pZCI6NywidXNlcm5hbWUiOiJ1c2VybmFtZTYifQ.EtMihjHJ2s_kWUrHBcXW2P8OxSqhIB6ZDKxtcsU3DV8
###
#Подтвердить заказ
POST {{baseUrl}}/order/confirm/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMTQ4OTMyLCJpYXQiOjE2OTMxNDUzMzIsImp0aSI6ImFjODdlMTIwNjc5NzRlYzk5YTI3ZGExMDMwMGMzOTk0IiwidXNlcl9pZCI6NiwidXNlcm5hbWUiOiJ1c2VybmFtZTUifQ.oAtA8oB42A_0HAm3nQXsJBNe462Cx2Xx97UiLYK1GcI

#######

# Получить токен 
POST {{baseUrl}}/token/
Content-Type: application/json

{
    "email":"shopowner@email.ru",
    "password":"shopowner"
}

###

# Получить магазины

GET  {{baseUrl}}/shop/

###

# Загрузить файл магазина
POST {{baseUrl}}/shop/upload/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyOTczNzk1LCJpYXQiOjE2OTI5NzAxOTUsImp0aSI6IjM3YjMwMjkxYjJkMjRhZDJiNTliZDI3MmM3ZGUwN2RjIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiIifQ.wSa7ocY5fKzULpY50QAHNnK4enl7s4UhJ22WooV8xhg
Content-Type: multipart/form-data
Content-Disposition: attachment; filename=shop.yaml

./shop1.yaml

###

#Обновление магазина
PATCH {{baseUrl}}/shop/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyODAwNTA1LCJpYXQiOjE2OTI3OTY5MDUsImp0aSI6Ijg2OGM0MjYxY2RkZDRmNmJiNjQ4MzJkMjJiMmUxNTQ3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiIifQ.j7ay0PInWxLS2jLZ3zmlxlwDyorufjIoV-lrhLSVgSY
Content-Type: application/json

{
    "name":"Связной",
    "url": "http://127.0.0.1:8000/api/shop/1",
    "categories": ["Смартфоны","Аксессуары","Flash-накопители"]
}

###
# Если категории отправить списком, то предыдущий список категорий заменяется новым
PATCH {{baseUrl}}/shop/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyODAwNTA1LCJpYXQiOjE2OTI3OTY5MDUsImp0aSI6Ijg2OGM0MjYxY2RkZDRmNmJiNjQ4MzJkMjJiMmUxNTQ3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiIifQ.j7ay0PInWxLS2jLZ3zmlxlwDyorufjIoV-lrhLSVgSY
Content-Type: application/json

{
    "categories": ["Тестовая категория 2"]
}

###
# Если строкой, то содержание строки добавляется к уже установленным категориям
PATCH {{baseUrl}}/shop/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyODAwNTA1LCJpYXQiOjE2OTI3OTY5MDUsImp0aSI6Ijg2OGM0MjYxY2RkZDRmNmJiNjQ4MzJkMjJiMmUxNTQ3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiIifQ.j7ay0PInWxLS2jLZ3zmlxlwDyorufjIoV-lrhLSVgSY
Content-Type: application/json

{
    "categories": "Тестовая категория 2"
}

###
# Посмотреть продукты
get {{baseUrl}}/product/
Content-Type: application/json
###
#Посмотреть продукт
get {{baseUrl}}/product/4216313
Content-Type: application/json
###
#Посмотреть карточку товара
get {{baseUrl}}/productinfo/4216313
Content-Type: application/json
###
# Создать продукт
POST {{baseUrl}}/product/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyODA0NTczLCJpYXQiOjE2OTI4MDA5NzMsImp0aSI6ImU2MjBmZDZlNzEwMDQ5YTU4YmRjMGU3YmRhNTlhMTkzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiIifQ.__ABkCHds25S3OXyH4KthkgzDgXOY9m-zAZ5IQ946bk
Content-Type: application/json

{
    "name":"Тестовый продукт3",
    "categories":["Категория тестового продукта3","Категория2","Категория3"]
}
###
# Обновить продукт
PATCH {{baseUrl}}/product/66/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyODA0NTczLCJpYXQiOjE2OTI4MDA5NzMsImp0aSI6ImU2MjBmZDZlNzEwMDQ5YTU4YmRjMGU3YmRhNTlhMTkzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiIifQ.__ABkCHds25S3OXyH4KthkgzDgXOY9m-zAZ5IQ946bk
Content-Type: application/json

{
    "name":"Новое имя",
    "categories": ["Новая категория"]
}

###
# Обновить карточку товара
PATCH {{baseUrl}}/productinfo/66/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyODE3NjY4LCJpYXQiOjE2OTI4MTQwNjgsImp0aSI6ImZjYjI4MGQ4ZWMyNTRhMmE4ZDgyYmFkNmJjMGRmMzliIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiIifQ.Ry-K_BonMCcnwEmZKyi7q_LxTHgLnQNdTvZubBe_7mc
Content-Type: application/json

{
  "quantity": 15.0,
  "parameters": [{"Param12":"19"}],
  "price": 17.0,
  "price_rrc": 18.0
}
