# Generated by Django 4.2.3 on 2023-08-23 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='app.ProductsCategories', to='app.category'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='parameters',
            field=models.ManyToManyField(blank=True, null=True, through='app.ProductsParameters', to='app.parameter', verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price_rrc',
            field=models.FloatField(default=0, verbose_name='разрешенная розничная цена без НДС '),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.shop', verbose_name='Компания'),
        ),
    ]
