# Generated by Django 4.2.3 on 2023-08-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_shops_alter_productinfo_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productparameter',
            old_name='Product_info',
            new_name='product_info',
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price_rrc',
            field=models.FloatField(verbose_name='разрешенная розничная цена без НДС '),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.TextField(verbose_name='Значение'),
        ),
    ]
