# Generated by Django 4.2.3 on 2023-08-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_shops_categories_shopscategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopscategories',
            old_name='categorys',
            new_name='categories',
        ),
    ]
